"""initial_migration_viatura_api

Revision ID: 2856ad880b46
Revises: None
Create Date: 2025-11-03 21:01:49.992344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2856ad880b46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano_de_manutencaos',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('unidade_operacionals',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('viaturas',
    sa.Column('placa', sa.String(length=7), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=False),
    sa.Column('unidade_operacional_id', sa.Integer(), nullable=False),
    sa.Column('plano_manutencao_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['plano_manutencao_id'], ['plano_de_manutencaos.id'], ),
    sa.ForeignKeyConstraint(['unidade_operacional_id'], ['unidade_operacionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('viaturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viaturas_placa'), ['placa'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viaturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viaturas_placa'))

    op.drop_table('viaturas')
    op.drop_table('unidade_operacionals')
    op.drop_table('plano_de_manutencaos')
    # ### end Alembic commands ###