"""adiciona custo plano e dados viatura

Revision ID: 6aa6b54285b3
Revises: 2856ad880b46
Create Date: 2025-11-28 22:49:30.828141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aa6b54285b3'
down_revision = '2856ad880b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano_de_manutencaos', schema=None) as batch_op:
        batch_op.add_column('plano_de_manutencaos', sa.Column('valor_estimado', sa.Float(), nullable=False, server_default='0'))

    with op.batch_alter_table('viaturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marca', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('cor', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viaturas', schema=None) as batch_op:
        batch_op.drop_column('cor')
        batch_op.drop_column('marca')

    with op.batch_alter_table('plano_de_manutencaos', schema=None) as batch_op:
        batch_op.drop_column('valor_estimado')

    # ### end Alembic commands ###